# Generated by Django 5.0.6 on 2024-06-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
